# .goreleaser.yml
version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./main/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).