# .goreleaser.yml
version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./main/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
brews:
  -
    name: "gohead"
    tap:
      owner: "gohead-cms"
      name: "homebrew-tap"
    url_template: "https://github.com/gohead-cms/gohead/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: "gohead-contrib"
      email: "gohead-cms@proton.me"
    homepage: "https://github.com/"
    description: "A brief description of your application"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
