receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

exporters:
  jaeger:
    endpoint: "http://localhost:14268/api/traces"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]