services:
  postgres:
    image: postgres:14
    container_name: gohead-postgres
    environment:
      POSTGRES_USER: gohead_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gohead
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - test-network

  mysql:
    image: mysql:8.0
    container_name: gohead-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: gohead_user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: gohead
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - test-network

  redis:
    image: redis:7-alpine
    container_name: gohead-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - test-network
    restart: always

volumes:
  postgres-data:
  mysql-data:
  redis-data: # NEW: Volume for Redis data persistence

networks:
  test-network: