site_name: GoHead
site_description: GoHead Documentation
site_author: GoHead Contributors
site_url: https://doc.gohead.com
dev_addr: 0.0.0.0:8000

repo_name: 'GoHead!'
repo_url: 'https://github.com/gohead-cms/gohead'

docs_dir: 'content'

theme:
  name: 'material'
  language: en
  include_sidebar: true
  favicon: assets/pic/gohead_logo.png
  logo: assets/pic/gohead_logo.png
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: 'GoHead • Copyright &copy; 2025'

extra_javascript:
  - assets/js/highlight.min.js

plugins:
  - search

markdown_extensions:
  - meta
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - markdown_include.include:
      base_path: content/includes/
      encoding: utf-8
  - toc:
      permalink: true

# Page tree
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started':
      - 'Overview': 'getting-started/overview.md'

