
name: GoReleaser

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5' # As specified in your go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # The version of GoReleaser to use. 'latest' is usually fine.
          version: latest
          # The arguments to pass to GoReleaser.
          # '--release-notes' can be used to pass a file with release notes.
          # '--rm-dist' cleans up the 'dist' directory before building.
          args: release --rm-dist
        env:
          # The GITHUB_TOKEN is required to create the release on GitHub.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The HOMEBREW_TAP_TOKEN is required for publishing to your Homebrew tap.
          # You must create this secret in your repository settings.
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

